### ISSUE TITLE
Rename to `pow`?

### ISSUE THREAD

**Issue by kgryte** [compute-io/power#1]
`power` follows the Matlab naming convention, but I am wondering if we should not deviate slightly to be aligned with the Javascript naming convention `pow`. Thoughts?

**Comment by Planeshifter** [comment]
Was not sure about this, either, as you can glance from looking at the test files where I always import the module as `pow`. I went with the non-abbreviated form as is more descriptive and other modules such as `multiply` also do not use short forms such as `mult`.

**Comment by kgryte** [comment]
We are not particularly consistent in this regard: `multiply`, `divide`, `subtract`, `add`, but then `exp`, `log`, `prod`, `sum`, etc. I might argue that, if users are familiar with `Math#pow`, then needing to be more descriptive is less of a factor. But I am fine with either. Your call.

**Comment by Planeshifter** [comment]
You are certainly right, and I don't mind renaming the module to align it with the naming of the JavaScript `Math.pow` function. `prod` is a good example where we did not choose the non-abbreviated form, so we are certainly less consistent than I thought.

**Comment by kgryte** [comment]
Alas. The burden of consistency. Naming often comes down more to personal taste.

**Comment by Planeshifter** [comment]
Given that we now have a `math-power` package and `math-pow` is a module name already taken by someone else, we should not rename this module. Closing this issue now.

**Comment by kgryte** [comment]
Agreed.
